name: Terraform-Deploy-az
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
permissions:
  contents: read
jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: vikrant
        uses: actions/checkout@v2
        with: 
          repository: swaranjalsingh/AzCiCD
          ref: 'main'
          token: ${{ secrets.SWARA }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure Azure credentials
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.CLIENT_ID }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}"}'
      - name: Terraform Init
        run: |
          cd childmodule
          terraform init
      - name: Terraform Plan
        run: |
          cd childmodule
          terraform plan
      - name: Terraform Apply
        run: |
          cd childmodule
          terraform apply -auto-approve
   
      - name: setup git config
        run: |
          git config --global user.name swaranjalsingh
          git config --global user.email swaranjal3905@gmail.com

          git add ./childmodule
          git commit -m "Updated websi"
          git push 
